### ISSUE TITLE
Write a function to hash user passwords

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#10]
Write a function in [`utils > password.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/utils/password.js) that will convert a password string to a secured hash. You can use `SECRET` environment variable if required. Return type should be string.

**Comment by Aman1143** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Congratulations on your first assigned issue. You have 48 hours for this task.
Happy Contributing!!

**Comment by DhruvHeisenberg** [comment]
claim

**Comment by BuddyLongLegs** [comment]
@DhruvHeisenberg The issue has already been assigned. Come back later for another issue.
