### ISSUE TITLE
Add collaborators

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#105]
Create a function to send invitation link to Collaborators via email. You will need to generate the JWT token with expiry 7 days and the following payload:
```json
{
  "projectId": "projectId",
  "collaborators": "all invited collaborator emails joined using ';'"
}
```
Also instead of storing collaborators email in database, invite them using this function while creating and updating the project.

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by GammaMicrowave** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07
