### ISSUE TITLE
Fix createForm

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/SaveMyForm-Backend#108]
While solving my current issue regarding formDashboard, I found out that our createForm function is slightly outdated as it does not have schema mentioned in the forms model. This is causing an error when I try to create a form to check my formDashboard, So I am making this issue so that I can solve that while also solving my previous task.

**Comment by BuddyLongLegs** [comment]
Thank you for raising this issue

**Comment by BuddyLongLegs** [comment]
Will you be able to solve it?
