### ISSUE TITLE
Fix Collaborator mails

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#123]
- Create new model (in mongodb) to store invited collaborators and their status
- Disable adding collaborators while creating new project / updating a project.
- use a separate route to add/update/remove collaborator.
- Send invite link to new collaborators
- Accept/Reject invites from people.

**Comment by chandra1899** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned @chandra1899

**Comment by chandra1899** [comment]
sir ,  who are collaborators here?
