### ISSUE TITLE
Write a function to create JWT token from JavaScript Object.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#17]
Write a function that takes JavaScript Object as an argument and returns a string which is a JWT token for that Object. Complete this function in the file [`utils > password.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/utils/password.js) and you have to use the `SECRET` environment variable for the key for creating the JWT token.

Do not forget to pull before starting your work.

**Comment by vedant-z** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
@vedant-z Congratulations!! This issue is assigned to you, you have 48 hours to complete to you

**Comment by Kali-Decoder** [comment]
Claim
