### ISSUE TITLE
Create the Login functionaity for the project.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#21]
Like every other application, this also requires login functionality. The basic process of this functionality for a REST API is to first check the user credentials and return an error response if they are wrong. On successful verification of the user's credentials, the server should return a secret (JWT token in this case) to the User. The same secret will same be used in the future to verify which user is raising a request to the server.

---

## The Task

The *Login* functionality will be written in a function in the file [`controllers > auth.controller.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/controllers/auth.controller.js). The function attributes are the default attributes of a request handling function, i.e., `(req, res)`. 

The request structure can be found [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#auth-endpoints). The Response structure is also present here.

For checking the password, you will have to first convert the password into hash, the `hash_password` function present in the [`utils > password.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/utils/password.js) should help in converting password into hash. Now you will have to match this hash to the password stored in the database.

We will also be applying ReCaptcha validation in login, for that, you can use the `verifycaptcha` function present in the [`utils > recaptcha.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/utils/recaptcha.js). 

Once the user is successfully verified, you will have to create a User Secret, which is actually a JWT token. For creating this JWT token, you have to use the `getJwt` function present in the [`utils > password.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/utils/password.js) and the structure of payload object for this function is this:
```json
{
    "id": "the _id of the MongoDB object of user",
    "email": "test@test.com"
}
```

To make returning a response easier, some pre-defined response functions according to the status code of the response are written in [`utils > responseCodes.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/utils/responseCodes.js). It is recommended to use them for returning successful or error response. The message passed to this function should be something related to the response, as they are for developer reference, the data passed to this function is the same as present in the Response structure present in [this](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#auth-endpoints) file.

---
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible. 

**All the Best!!**

**Comment by GammaMicrowave** [comment]
claim

**Comment by frikinomad** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
Assigned to @GammaMicrowave. All the Best!!

**Comment by Siddhant-Agarwal4583** [comment]
claim
