### ISSUE TITLE
Complete the function to verify ReCaptcha

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#22]
The function `verifycaptcha` is present in the file [`utils > recaptcha.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/utils/recaptcha.js) but it only returns `true` ¯\\\_(ツ)\_/¯. Complete the function to verify a Recaptcha token received through the argument.

> **Note**
> * The Site Key for Recaptcha verification should be stored in an environment variable named `GOOGLE_RECAPTCHA_SITE_KEY`.
> * The Site Secret Key for Recaptcha verification should be stored in an environment variable named `GOOGLE_RECAPTCHA_SECRET_KEY`.
> * For the development environment, the function should always return `true`. Set the `ENV` environment variable to `dev` for the development environment and `prod` for the production environment.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by frikinomad** [comment]
Claim

**Comment by SyedMa3** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
Assigned to @frikinomad. All The Best!!

**Comment by BuddyLongLegs** [comment]
The function should only return either `true` or `false`, sorry for not mentioning earlier.

**Comment by Siddhant-Agarwal4583** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Issue is open for claims.

**Comment by Shubhankit-Pandey** [comment]
Claim

**Comment by pavanvnk** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
Assigned to @Shubhankit-Pandey. All the Best!!

**Comment by BuddyLongLegs** [comment]
@Shubhankit-Pandey Updates?

**Comment by Kali-Decoder** [comment]
Claim
