### ISSUE TITLE
Uninstall a library

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#24]
An unwanted library named `passport` is present in the project. It has been used in auth.config.js which itself is not useful. 

Uninstall this library, delete the file auth.config.js and remove every occurrence of both the library and this file in the entire project.

---

Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible. 

**All the Best!!**

**Comment by Aniketkumar121** [comment]
claim

**Comment by Shubhankit-Pandey** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
@Aniketkumar121 you discord username?

**Comment by BuddyLongLegs** [comment]
Assigned to @Shubhankit-Pandey. All the Best!!

**Comment by Aniketkumar121** [comment]
Aniket#0600

**Comment by Aniketkumar121** [comment]
Sir thats not fair

**Comment by Aniketkumar121** [comment]
Sir that's not fair you had assigned this issue to someone else but I had
commented first for claiming.

**Comment by BuddyLongLegs** [comment]
@Aniketkumar121 Please use the SaveMyForm-Backend Discord Channel for discussion

**Comment by Aniketkumar121** [comment]
ok sir

**Comment by BuddyLongLegs** [comment]
Assigned to @Aniketkumar121. All the Best!!

**Comment by Siddhant-Agarwal4583** [comment]
claim

**Comment by Kali-Decoder** [comment]
claim
