### ISSUE TITLE
Write a function to send EMail to users

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#25]
In the file [`utils > mailer.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/utils/mailer.js) write a function that takes three arguments: `email`, `body`, `html` and sends an email with the body and HTML to the email provided in the argument. 

For this, you can use the library `nodemailer`. The email should be sent using a Gmail account. For testing you will need to create an [App Password](https://support.google.com/accounts/answer/185833?hl=en) for your Gmail account.

>**Note**
> * Email address should be stored in an environment variable named `MAIL_ADDRESS`.
> * Application Password of that Gmail account should be stored in an environment variable named `MAIL_PASSWORD`.

---

Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible. 

**All the Best!!**

**Comment by akshatsgh** [comment]
claim

**Comment by pavanvnk** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
@akshatsgh and @pavanvnk your discord?

**Comment by akshatsgh** [comment]
strange#0227

**Comment by pavanvnk** [comment]
Pavan #2957

**Comment by BuddyLongLegs** [comment]
Assigned to @pavanvnk! All the Best!!
