### ISSUE TITLE
Change CORS policy.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#31]
Change the CORS policy of the application to allow every origin. For this you can use the `cors` library which is already installed in the project.

---

Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible. 

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07. All the Best!!

**Comment by antsharma** [comment]
claim

**Comment by Aman1143** [comment]
claim
