### ISSUE TITLE
Create Email Verification Template.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#33]
An email template is basically an HTML file which **DOES NOT** support javascript. You have to create an email template for an email that will be sent to users for verifying their email address. For that, they will receive a link in the mail that they will have to open. You can use styling and fill in temporary data for the user's name, verification link, etc. 

You can be any creative with the design and structure of the email, as long as it serves the purpose.

---
### How to submit?
* No need to claim, the issue is open for all.
* Create a file named `verification-<Github Username>.html` in the email-template directory.
* No external CSS files are allowed, write the styling in the HTML file itself.
* Include the screenshot in your PR.

---

You can find the color palette for the project SaveMyForm here: [Figma File](https://www.figma.com/file/2KnOYD17aRMhXw8qhuuEKu/Theme?node-id=0%3A1&t=cjSwkQnMKPur2bc1-1)

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by akshatsgh** [comment]
claim

**Comment by pavanvnk** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
No need to claim this issue, it's open for all.

**Comment by Aniketkumar121** [comment]
claim
