### ISSUE TITLE
Add an `allowRecaptcha` boolean field in the project model.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#36]
In the project model at [`models > project.model.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/models/project.model.js). Add a field named `allowRecaptcha` in that model which will be a Boolean field with default value `false`.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by frikinomad** [comment]
Claim

**Comment by pavanvnk** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
Assigned to @frikinomad. All the Best!!
