### ISSUE TITLE
Creating a middleware for checking if users are authenticated or not.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#38]
In the [`middlewares > auth.middleware.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/middlewares/auth.middleware.js) create a function with arguments: `(req, res, next)` and export as default export of the file. 
Working of the function:
- Check if there is an `Authorization` header present in the request. If there is, its format should be `Bearer <token>`. 
- Absence of this header means the request is unauthorized.
- Extract the `token` from the `Authorization` header and verify this token if it is valid and has not expired yet.
- If the token is verified set `req.isAuthenticated = true` otherwise set `req.isAuthenticated = false`.
- The User's details will be available in the payload, you will have to find the user in the database using these details and save it to `req.user`.

>**Note**
>Once you are assigned this issue, you can ask me for a test JWT token, for testing your function.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by Im-Madhur-Gupta** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @Im-Madhur-Gupta. All the Best!!

**Comment by Kali-Decoder** [comment]
claim

**Comment by BuddyLongLegs** [comment]
@Im-Madhur-Gupta Updates?

**Comment by Im-Madhur-Gupta** [comment]
@BuddyLongLegs I'll be able to complete this by tonight.

**Comment by BuddyLongLegs** [comment]
Great!!

**Comment by Im-Madhur-Gupta** [comment]
@BuddyLongLegs Need the sample JWT and the env vars to test the middleware.
