### ISSUE TITLE
Add the feature Google OAuth2.0

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#40]
Create a controller function in [`controllers > auth.controller.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/controllers/auth.controller.js) with arguments `(req, res)`. For this task, you can refer to [this](https://blog.prototypr.io/how-to-build-google-login-into-a-react-app-and-node-express-api-821d049ee670) blog.
>**Note**
> - You will receive the token in the request body, you can check the query structure [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#auth-endpoints).
> - The library `google-auth-library` is already installed in the project.
> - The Google Client id should be stored in the environment variable `GOOGLE_OAUTH_CLIENT_ID`.
> - The Google Client Secret should be stored in the environment variable `GOOGLE_OAUTH_CLIENT_SECRET`.

### Process:
- Extract the `name` and `email` of the user from the payload.
- Check if a user already exists with the same email, if yes then you will have to directly send the JWT token, along with other information as sent in the `logIn` function present in the same file.
- If the user does not exist, you will have to create a new user with the name and email received in the payload, remember to set the password to a blank string `""` and send the JWT token, along with other information as sent in the `signUp` function present in the same file.
- Add a post route with path `"/auth/google"` and this function as the controller in the file [`routes > auth.routes.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/routes/auth.routes.js)

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by frikinomad** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07. All the Best!!

**Comment by Kali-Decoder** [comment]
claim

**Comment by BuddyLongLegs** [comment]
@SanyamAgrawal07 updates?

**Comment by Kali-Decoder** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
The issue will be open for claims again once the assignee drop out of it.

**Comment by frikinomad** [comment]
claim

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs On it

**Comment by Kali-Decoder** [comment]
claim
