### ISSUE TITLE
Add one more check in logIn controller function.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#41]
In the `logIn` controller function, present in [`controllers > auth.controller.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/controllers/auth.controller.js) add one more check that if the `passwordHash` of the user in the database is a blank string, i.e., `""`, then it should return a `400 response` with error message: `"Account created using Google Auth, either change your password or Signin with Google"`

**Comment by pavanvnk** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
Assigned to @pavanvnk. All the Best!!
