### ISSUE TITLE
Send Bad Response for missing fields

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#47]
In the `logIn`, `signUp` and `authGoogle` functions, present in [`controllers > auth.controller.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/controllers/auth.controller.js), check if any field is missing in the request and return a `400` response if so.

API structure: [API_endpoints.md](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#auth-endpoints)

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07. All the Best!!
