### ISSUE TITLE
Complete the function that sends Email verification link to the user.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#54]
In the file [`utils > mailer.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/utils/mailer.js) there is a function `sendVerificationLink` that is supposed to send the link generated in it to the email provided to it as an argument. The email body is present in the form of a handlebar file in [`templates > verification.handlebar`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/templates/verification.handlebar).

You will have to install the package `nodemailer-express-handlebars` to send this email with the link to the user.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07. All the Best!!
