### ISSUE TITLE
Improve a function

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#56]
Currently the function `getJwt` present in [`utils > password.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/utils/password.js) only creates a JWT with expiry of 30 days, the task is to make this expiry the argument of the function, and default it to 30 days if expiry is not passed in the arguments.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07. All the best!!
