### ISSUE TITLE
Complete the route to send to Verification link to users.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#58]
Create a function in `controllers > user.controller.js` that on request from an unverified user will send a Verification link to him/her. FOr verification secret, create a JWT of expiry 5 minutes with payload: 
```json
{
    "name": "User Name",
    "email": "test@test.com",
    "id": "mongodbid",
    "ip": "IP Address of the origin of request"
}
```

>**Note**
>- The function to send verification email is present in `utils > mailer.js`.
>- The function to create JWT token is present in `utils > password.js`.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by GammaMicrowave** [comment]
claim

**Comment by BuddyLongLegs** [comment]
@GammaMicrowave  has 3 issues assigned, so assigning to @SanyamAgrawal07. All the Best!!

**Comment by BuddyLongLegs** [comment]
@SanyamAgrawal07 request structure is present [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#raiseverification)
