### ISSUE TITLE
Create the route that verifies user emails

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#59]
Create the route that takes JWT secret from the request path and verifies the token to get the user details stored in the payload. Mark the user as verified if not already verified, otherwise send bad response.

Request structure is present [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#verifysecret).

You have to write the controller function in `controllers > user.controller.js`.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by GammaMicrowave** [comment]
claim

**Comment by Im-Madhur-Gupta** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
@GammaMicrowave you already have 3 issues assigned to you.

**Comment by BuddyLongLegs** [comment]
Assigned to @Im-Madhur-Gupta. All the Best!!

**Comment by BuddyLongLegs** [comment]
@Im-Madhur-Gupta updates?

**Comment by Im-Madhur-Gupta** [comment]
Hey @BuddyLongLegs, I have raised a PR for this, please check and lmk if any changes are req.
