### ISSUE TITLE
Create User model

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#6]
Create the user database model in the [`models > user.model.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/models/user.model.js) file. The information regarding the same is available in the [`README.md`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/README.md) file.

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Congratulations on your first assigned issue. You have 48 hours for this task.
Happy Contributing!!

**Comment by Aman1143** [comment]
claim

**Comment by BuddyLongLegs** [comment]
@Aman1143 Issue has already been assigned

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs Should I do some basic validation for name and email like required/trim or just the basic structure for the model is acceptable??

**Comment by BuddyLongLegs** [comment]
Sure, doing so is recommended
