### ISSUE TITLE
Create the update user route controller.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#61]
In the `controllers > user.controller.js` create a function that will act as the controller for the update user route. Remember to check the password before updating user information. There is also an optional newPassword field that when provided and is not empty string will update the user's password. Ignore the oldPassword in the request if the password of the user stored in Database is an empty string. Keep in mind all the required fields should be present in the response otherwise you'll have to return a bad response. If the newPassword's length is less than 6 you should not save the other changes too.

The request structure is present [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#update).

For creating passwordHash you have to use the function present in the file `utils > password.js`.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07
