### ISSUE TITLE
Write the controller function to change user's password

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#63]
Request Structure is present [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#updatepassword)

> **Note**
> - You'll have to check user's old password before setting new one.
> - Also verify recaptcha.
> - You'll have to write the function in `controllers > user.controller.js`.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07
