### ISSUE TITLE
Who Am I?

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#65]
Write the controller for the user to get his basic details.
Request Structure [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#self).

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
Claim

**Comment by GammaMicrowave** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07
