### ISSUE TITLE
Write the function for the user dashboard.

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#66]
Request Structure [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#dashboard).

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by GammaMicrowave** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @GammaMicrowave

**Comment by Kali-Decoder** [comment]
Claim
