### ISSUE TITLE
One more Middle Man

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#67]
Create a new middleware `verifyMiddleware` that is similar to the `authMiddleware` but now, it also returns `not allowed` response if user is not verified.

You will have to create the middleware in a new file name `verify.middleware.js` in the `middlewares` directory.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by TheDivineAurora** [comment]
CLAIM

**Comment by BuddyLongLegs** [comment]
Assigned to @TheDivineAurora

**Comment by Kali-Decoder** [comment]
Claim
