### ISSUE TITLE
Create Project Model

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#7]
Create the project database model in the [`models > project.model.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/models/project.model.js) file. The information regarding the same is available in the [`README.md`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/README.md) file.

**Comment by vedant-z** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
Congratulations on your first assigned issue. You have 48 hours for this task.
Happy Contributing!!
