### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#72]
Write the controller function to create a new project. No will need to add respective checks in the function. The function should be written in `controllers > project.controller.js`. The request structure is present [here}(https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#new). 

**Do not forget to check recaptcha**

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07
