### ISSUE TITLE
Create User Routes

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#75]
From reading the docs [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#user-endpoints), create user routes with respective restrictions. Controller functions are present in `controllers > user.controller.js`, auth and verify middlewares are present in `middlewares` folder.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by GammaMicrowave** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @GammaMicrowave

**Comment by GammaMicrowave** [comment]
clem take 2
