### ISSUE TITLE
Update Project

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#77]
Write the controller function to update project details.
**Restrictions:** Only the owner is allowed to update project details.
Request Structure is present [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#updateid)

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by Im-Madhur-Gupta** [comment]
Claim

**Comment by GammaMicrowave** [comment]
cakjwenfa

**Comment by BuddyLongLegs** [comment]
Assigned to @Im-Madhur-Gupta

**Comment by BuddyLongLegs** [comment]
@Im-Madhur-Gupta updates?

**Comment by Im-Madhur-Gupta** [comment]
@BuddyLongLegs I have raised a PR, lmk if changes are required.
