### ISSUE TITLE
Project Dashboard

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#78]
Write the function to send project dashboard details. 
**Restrictions:** Only users and collaborators can view dashboard details.
Request Structure [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#dashboardid)

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07

**Comment by Kali-Decoder** [comment]
Claim
