### ISSUE TITLE
Delete Project

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#79]
Delete the project.
**Restrictions:** Only owner can delete.
Request Structure [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#deleteid)

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by GammaMicrowave** [comment]
cawwae

**Comment by GammaMicrowave** [comment]
clem

**Comment by BuddyLongLegs** [comment]
Couldn't understand

**Comment by GammaMicrowave** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @GammaMicrowave

**Comment by BuddyLongLegs** [comment]
@GammaMicrowave updates

**Comment by GammaMicrowave** [comment]
Discord pe bhi likh sakta hai ye na?
