### ISSUE TITLE
Create Form model

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#8]
Create the form database model in the [`models > form.model.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/models/form.model.js) file. The information regarding the same is available in the [`README.md`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/README.md) file.

**Comment by Aman1143** [comment]
claim

**Comment by BuddyLongLegs** [comment]
@Aman1143 You already have an assigned issue in this repository, please complete that first then claim another issue

**Comment by Aman1143** [comment]
ok

**Comment by abhinav-raja** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Congratulations @abhinav-raja on your first assigned issue. You have 48 hours for this task.
Happy Contributing!!

**Comment by Phantom-Harsh** [comment]
Claim

**Comment by SanyamAgrawal07** [comment]
is this open for claims?
