### ISSUE TITLE
Routes to Project

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#84]
Complete the project routes in `routes/project.routes.js`.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by Im-Madhur-Gupta** [comment]
Claim

**Comment by BuddyLongLegs** [comment]
Assigned to @Im-Madhur-Gupta

**Comment by BuddyLongLegs** [comment]
@Im-Madhur-Gupta updates?

**Comment by Im-Madhur-Gupta** [comment]
@BuddyLongLegs please check your Discord DMs once, thanks.
