### ISSUE TITLE
GridFS

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#85]
Initialize GridFS file storage in the project. Write the database configuration in `config/db.config.js`. Also, link the library `multer` with GridFS by creating middleware for it in `file.middleware.js`. Bucket Name: `"uploads"`. Assignee can contact me on Discord for more information, if required.

You can install the required libraries.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by SanyamAgrawal07** [comment]
cclaim

**Comment by BuddyLongLegs** [comment]
Assigned to @SanyamAgrawal07

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs I have made the PR #86 for this issue
