### ISSUE TITLE
Create FormSubmission model

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#9]
Create the formSubmission database model in the [`models > formSubmissions.model.js`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/models/formSubmissions.model.js) file. The information regarding the same is available in the [`README.md`](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/README.md) file.

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Congratulations on your first assigned issue. You have 48 hours for this task.
Happy Contributing!!
